CREATE OR REPLACE TYPE "MY_TABLE_OBJ" AS OBJECT
(
  "PK"       NUMBER,
  "COLUMN_1" VARCHAR2(12 BYTE),
  "COLUMN_2" CLOB
);
CREATE OR REPLACE TYPE "MY_ARRAY" AS TABLE OF MY_TABLE_OBJ;
CREATE OR REPLACE TYPE "MY_NARRAY" AS TABLE OF NUMBER;
